---
version: "3"
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=Test
    ports:
      - 5432:5432
    container_name: postgres
  mysql:
    image: mysql
    ports:
     - 3306:3306
    environment:
     - MYSQL_ROOT_PASSWORD=mysql
     - MYSQL_USER=myuser
     - MYSQL_PASSWORD=123456
     - MYSQL_DATABASE=Test
    container_name: mysql
  #======================= Kafka ======================
  message_queue:
    extends:
      file: ../../docker/docker-compose.yml
      service: message_queue
  connect:
    image: debezium/connect:2.2
    build:
      context: debezium-jdbc
      args:
        DEBEZIUM_VERSION: 2.2
    ports:
     - 8083:8083
     - 5005:5005
    links:
     - message_queue
     - postgres
     - mysql
    environment:
     - BOOTSTRAP_SERVERS=message_queue:29092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_source_connect_statuses
    container_name: connect
volumes:
  message_queue:
    external: false
name: risingwave-compose
