[package]
name = "my_udf"
version = "0.1.0"
edition = "2021"
homepage = "https://github.com/risingwavelabs/risingwave"
license = "Apache-2.0"
repository = "https://github.com/risingwavelabs/risingwave"

[workspace]

[dependencies]
wit-bindgen = "0.16"
arrow-array = "49"
arrow-schema = "49"
arrow-ipc = "49"
arrow = "49"
arrow-data = "49"
arrow-buffer = "49"


[lib]
crate-type = ["cdylib"]
