[meta]
disable_recovery = true
max_heartbeat_interval_secs = 600

[storage]
imm_merge_threshold = 2

[system]
barrier_interval_ms = 250
checkpoint_frequency = 1
max_concurrent_creating_streaming_jobs = 0
