# Flags for enabling SIMD on aarch64 targets.
# Remove "-Ctarget-feature=+avx2" if your x86_64 target does not support AVX2 vector extensions
[target.'cfg(target_arch = "x86_64")']
rustflags = ["-Ctarget-feature=+avx2"]

# Flags for enabling SIMD on aarch64 targets.
# Remove "-Ctarget-feature=+neon" if your aarch64 target does not support NEON vector extensions
[target.'cfg(target_arch = "aarch64")']
rustflags = ["-Ctarget-feature=+neon"]

# Flags for linux targets.
[target.'cfg(target_os = "linux")']
rustflags = ["-Clink-arg=-fuse-ld=lld", "-Clink-arg=-Wl,--no-rosegment"]

# Hacks for https://github.com/rust-lang/cargo/issues/11166
# FIXME: madsim doesn't work either
[target.x86_64-unknown-linux-gnu]
rustflags = ["--cfg", "tokio_unstable"]
[target.aarch64-unknown-linux-gnu]
rustflags = ["--cfg", "tokio_unstable"]
[target.x86_64-apple-darwin]
rustflags = ["--cfg", "tokio_unstable"]
[target.aarch64-apple-darwin]
rustflags = ["--cfg", "tokio_unstable"]

# Flags for all targets.
[target.'cfg(all())']
rustflags = [
    # lints
    # TODO: use lint configuration in cargo https://github.com/rust-lang/cargo/issues/5034
    "-Funused_must_use",
    "-Wclippy::dbg_macro",
    "-Wclippy::disallowed_methods",
    "-Wclippy::disallowed_types",
    "-Wclippy::doc_markdown",
    "-Wclippy::explicit_into_iter_loop",
    "-Wclippy::explicit_iter_loop",
    "-Wclippy::inconsistent_struct_constructor",
    "-Wclippy::unused_async",
    "-Wclippy::map_flatten",
    "-Wclippy::no_effect_underscore_binding",
    "-Wclippy::await_holding_lock",
    "-Wrustdoc::broken_intra_doc_links",
    "-Wfuture_incompatible",
    "-Wnonstandard_style",
    "-Wrust_2018_idioms",
]
