version: '3.8'

services:
  message_queue:
    extends:
      file: ../../docker/docker-compose-with-minio.yml
      service: message_queue

  ingestor:
    image: "docker.vectorized.io/vectorized/redpanda:latest"
    volumes:
      - './records.bin:/data/records.bin'
    depends_on:
      - message_queue
    command:
      - topic produce --brokers message_queue:29092 'alltypes' < /data/records.bin

  risingwave:
    image: ghcr.io/risingwavelabs/risingwave:latest
    ports:
      - 4566:4566
      - 5691:5691
    command:
      - playground
    container_name: risingwave

volumes:
  redpandadata:
    driver: local
