[package]
name = "risingwave_sink_impl"
version = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[package.metadata.cargo-machete]
ignored = ["workspace-hack"]

[package.metadata.cargo-udeps.ignore]
normal = ["workspace-hack"]

[dependencies]
anyhow = "1"
arrow-array = { workspace = true }
arrow-schema = { workspace = true }
async-nats = "0.32"
async-trait = "0.1"
aws-sdk-kinesis = { workspace = true }
base64 = "0.21"
bytes = { version = "1", features = ["serde"] }
clickhouse = { git = "https://github.com/risingwavelabs/clickhouse.rs", rev = "622501c1c98c80baaf578c716d6903dde947804e", features = [
    "time",
] }
ctor = "0.2"
futures = { version = "0.3", default-features = false, features = ["alloc"] }
http = "0.2"
hyper = { version = "0.14", features = [
    "client",
    "tcp",
    "http1",
    "http2",
    "stream",
] }
hyper-tls = "0.5"
icelake = { workspace = true }
itertools = "0.11"
jni = { version = "0.21.1", features = ["invocation"] }
maplit = "1.0.2"
parking_lot = "0.12"
prost = { version = "0.12", features = ["no-recursion-limit"] }
pulsar = { version = "6.0", default-features = false, features = [
    "tokio-runtime",
    "telemetry",
    "auth-oauth2",
] }
rdkafka = { workspace = true, features = [
    "cmake-build",
    # "ssl",
    # FIXME: temporary workaround before we find an ideal solution.
    # See why it's needed and why it's not ideal in https://github.com/risingwavelabs/risingwave/issues/9852
    "ssl-vendored",
    "gssapi",
    "zstd",
] }
redis = { version = "0.23.3", features = ["aio", "tokio-comp", "async-std-comp"] }
regex = "1.4"
risingwave_common = { workspace = true }
risingwave_connector = { workspace = true }
risingwave_jni_core = { workspace = true }
risingwave_pb = { workspace = true }
risingwave_rpc_client = { workspace = true }
risingwave_sqlparser = { workspace = true }
serde = { version = "1", features = ["derive", "rc"] }
serde_derive = "1"
serde_json = "1"
serde_with = { version = "3", features = ["json"] }
strum = "0.25"
strum_macros = "0.25"
time = "0.3.28"
tokio = { version = "0.2", package = "madsim-tokio", features = [
    "rt",
    "rt-multi-thread",
    "sync",
    "macros",
    "time",
    "signal",
    "fs",
] }
tokio-retry = "0.3"
tokio-stream = "0.1"
tracing = "0.1"
url = "2"

[target.'cfg(not(madsim))'.dependencies]
workspace-hack = { path = "../../workspace-hack" }

[dev-dependencies]
criterion = { workspace = true, features = ["async_tokio", "async"] }
rand = "0.8"
tempfile = "3"
tracing-test = "0.2"

[build-dependencies]
prost-build = "0.12"

[lints]
workspace = true
