version: '3.1'

services:
  mongodb:
    extends: ../mongodb/docker-compose.yaml
    service: mongodb

  mongodb-setup:
    extends: ../mongodb/docker-compose.yaml
    service: mongodb-setup

  random_data_generator:
    extends: ../mongodb/docker-compose.yaml
    service: random_data_generator

