version: '3.1'

services:
  mongodb:
    image: mongodb/mongodb-community-server:4.4.23-ubi8
    container_name: mongodb
    ports:
      - "27017:27017"
    command: --replSet rs0 --oplogSize 128
    restart: always
    healthcheck:
      test: "echo 'db.runCommand({ping: 1})' | mongo"
      interval: 5s
      timeout: 10s
      retries: 3

  mongodb-setup:
    image: mongodb/mongodb-community-server:4.4.23-ubi8
    container_name: mongodb-setup
    depends_on:
      - mongodb
    entrypoint:
      [
        "bash",
        "-c",
        "sleep 10 && mongo --host mongodb:27017 /config-replica.js && sleep 10"
      ]
    restart: "no"
    volumes:
      - ./config-replica.js:/config-replica.js

  random_data_generator:
    build:
      context: .
      dockerfile: Dockerfile.generator
    container_name: random_data_generator
    depends_on:
      - mongodb
    environment:
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_DB_NAME: random_data
